language: node_js
node_js:
  - "8.9.0"

after_script: >
 NODE_ENV=test
 istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js &&
 node ./node_modules/.bin/codacy-coverage < ./coverage/lcov.info &&
 rm -rf ./coverage
